---

#file: /roles/paquetes_basicos/tasks/main.yml

- name: Run apt-get update
  apt:
    update_cache: yes


- name: Install list of packages
  apt: name={{item}} state=installed
  with_items:
       - vim
       - apache2
       - git

- hostname:
    name: phpipam