---

#file: /roles/php/tasks/main.yml

- name: Job(004) install php
  apt: name={{item}} state=present
  with_items:
    - php5-cli
    - php5-curl
    - php5-fpm
    - php5-intl
    - php5-json
    - php5-mcrypt
    - php-pear
    - libapache2-mod-php5 

