Vagrant.require_version ">= 1.7.0"
Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.gui = false
    virtualbox.customize [ 'modifyvm', :id, '--memory', '512' ]
    virtualbox.customize [ 'modifyvm', :id, '--nictype1', 'virtio' ]
    virtualbox.customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]
    virtualbox.customize [ 'modifyvm', :id, '--natdnsproxy1', 'on' ]
  end
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8081, id: "apache", protocol: "tcp", auto_correct: "true"
  config.vm.network "forwarded_port", guest: 22, host:2221, id: "ssh", auto_correct: true
  config.vm.network "forwarded_port", guest: 3306, host: 33061, id: "mysql", protocol: "tcp", auto_correct: "true"
  config.vm.network "private_network", ip: "99.99.99.99"
  config.vm.synced_folder "/home/jprado/vagrant_public", "/var/www/html"
  config.ssh.insert_key = false
  config.vm.provision "ansible" do |ansible|
    #ansible.verbose = 'vvv'
    ansible.playbook = "main.yml"
  end
end

