---
#file: /roles/apache/tasks/main.yml
 
- name: install apache2
  apt: name=apache2 state=latest update_cache=yes
  tags: apache
 
- name: install apache2-utils for authentication
  apt: name=apache2-utils state=latest update_cache=yes
  tags: apache
 
- name: enable mod_proxy module
  apache2_module: name={{item}} state=present
  with_items:
    - proxy
    - proxy_http
    - rewrite
    - headers
    - ssl
  notify: restart apache
  tags: apache

- copy:  
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: 0644
    backup: yes